### ISSUE TITLE
cross reference your blacklist/pull from ipfilter of emule security

### ISSUE THREAD

**Issue by xavier2k6** [ngosang/trackerslist#103]
cross reference your blacklist/pull from ipfilter of emule security.
updated frequently - usually once a month from here:
http://emule-security.org/

this should help weed out even more bad ip ranges/bad trackers.

**Comment by francisuk1989** [comment]
The only issue i have with level 1 blocklist been used is that most modern ISPs enforce dynamic IPs, Some of them IPs are fine but amazon, fake servers, bogon i agree on them been used.

**Comment by ngosang** [comment]
@xavier2k6 thank you! It's a great idea.
For now I don't have too much free time. I leet this open.

**Comment by ngosang** [comment]
@xavier2k6 I have been thinking in this but it's not really useful because of several reasons:
* These trackers are public and the connections are insecure. If you don't want to be seen use private trackers instead.
* It doesn't matter if some tracker returns fake peers. If one peer tries to send wrong/bad data, the data will be discarded and the peer banned after few megabytes. Bittorrent is more trustworthy than Emule in this scerario.
* I can't find any tracker IP in that lists
