### ISSUE TITLE
Please always include some http trackers in the tracker_best list

### ISSUE THREAD

**Issue by N46AN** [ngosang/trackerslist#168]
A lot of ISPs have strong traffic shaping upon UDP traffic, effectively disabling any contact to UDP tracker as well as DHT. "tracker_best" list is used by a lot of public torrent makers, so not including any http tracker can have negative effect. 

For example, recently tracker*.itzmx.com are removed from tracker_best list and this caused users from said ISP not being able to use a lot of recently made public torrents.

**Comment by ngosang** [comment]
Currently there are 2 http trackers in the best trackers list. The scoring algorithm doesn't take in count the protocol. More reliable and more used trackers are first in the list. Some operators running udp and http trackers requested me to put in the list only the udp tracker because it's really expensive for them to have high traffic with the http protocol.

> A lot of ISPs have strong traffic shaping upon UDP traffic, effectively disabling any contact to UDP tracker as well as DHT. "tracker_best" list is used by a lot of public torrent makers, so not including any http tracker can have negative effect.

Traffic shaping means slow speed, not blocking connections. Anyway, most of the communications between peers (file transfers) are done using UDP, so you are fucked up anyway...
