### ISSUE TITLE
Got a duplicate entry in 2019-07-23's trackers list

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [ngosang/trackerslist#182]
see https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt#L5
Is that because 2 urls got resoved to one same ip?

**Comment by kevinvanrijn** [comment]
Corrected links relative to when this issue was created:

https://github.com/ngosang/trackerslist/blob/eed568251aa65037d718d8f19ef09e698169e4d6/trackers_best_ip.txt#L3

＆

https://github.com/ngosang/trackerslist/blob/eed568251aa65037d718d8f19ef09e698169e4d6/trackers_best_ip.txt#L5

This IP address appears to be completely gone from the current master. I wonder if the IP would get duplicated again if the host were to return though.

From a quick Google search the IP appears to be related to both "open-internet.nl" and "leechers-paradise.org" so perhaps those are both being checked?

**Comment by ngosang** [comment]
Fixed. Thanks for reporting!
