### ISSUE TITLE
check tracker，thanks

### ISSUE THREAD

**Issue by OR120** [ngosang/trackerslist#191]
udp://9.rarbg.com:2710/announce
udp://9.rarbg.to:2710/announce
udp://9.rarbg.me:2710/announce

**Comment by OR120** [comment]
udp://tracker.ktxp.com:6868/announce
http://tracker.ktxp.com:6868/announce
udp://tracker.ktxp.com:7070/announce
http://tracker.ktxp.com:7070/announce

**Comment by ngosang** [comment]
> udp://9.rarbg.com:2710/announce
udp://9.rarbg.to:2710/announce
udp://9.rarbg.me:2710/announce

I'm listing only .to version, the others are blacklisted because they are sa same tracker (returns the same peers) => https://github.com/ngosang/trackerslist/blob/master/blacklist.txt

>udp://tracker.ktxp.com:6868/announce
http://tracker.ktxp.com:6868/announce
udp://tracker.ktxp.com:7070/announce
http://tracker.ktxp.com:7070/announce

Not working for here.
