### ISSUE TITLE
Which trackers have webtorrents?

### ISSUE THREAD

**Issue by 34r7h** [ngosang/trackerslist#237]
Or is there a way to search only for webtorrents?

**Comment by ngosang** [comment]
Webtorrent is a different protocol (similar to Bittorrent but not compatible). If you add webtorrent trackers to a `.torrent` file, most Bittorrent clients will ignore that trackers because they don't understand that protocol.
Webtorrent is not very popular, I don't know torrent sites which use or work with webtorrent. Major Bittorrent clients don't support that protocol. That's why I provide them is a separate list. They are useless for most users.

**Comment by 34r7h** [comment]
Gotcha, that makes sense. I guess webtorrents are more of a
local/private infrastructure tool than any promise for browser-only
file-sharing.
